name: two_stream_enc_dec
channels:
        - conda-forge
        - defaults
dependencies:
        - python=3.6
        - numpy=1.17.2
        - scikit-image=0.15.0
        - scikit-learn=0.21.3
        - pip=19.2.3
        - matplotlib=3.1.1
        - imageio=2.6.0
        - h5py=2.9.0
        - tqdm=4.30.0
        - pip:
                - scipy==1.1.0
                - opencv-python==4.1.2.30
                - tensorflow-gpu==2.3.1
                - keras==2.2.4
